/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /Users/thomasmatlock/Documents/Github/juxtaposition-web/public/models/meshes/MacbookM4/MacbookM4.gltf --output /Users/thomasmatlock/Documents/Github/juxtaposition-web/models/MacbookM4.tsx -r /models/meshes/MacbookM4 -t --resolution 512 --shadows --meta --keepmeshes --keepmaterials 
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame, useThree } from '@react-three/fiber';
import { useScroll, Detailed } from '@react-three/drei';
import { easing, geometry } from 'maath';
import UserContextProvider from '@/context/userContext';
import InputContextProvider from '@/context/inputContext';
import { useContext, useState } from 'react';
import pointerEventHandlers from './shared/pointerEventHandlers';

type GLTFResult = GLTF & {
	nodes: {
		['Macbook_Pro_16_Case_Space-Black001']: THREE.Mesh;
		['Macbook_Pro_16_Display_Base_Space-Black001']: THREE.Mesh;
		['Macbook_Pro_16_Display_Screen_Space-Black001']: THREE.Mesh;
		['Macbook_Pro_16_Keyboard_Space-Black001']: THREE.Mesh;
		['Macbook_Pro_16_Stand_Space-Black001']: THREE.Mesh;
		['Macbook_Pro_16_Case_Space-Black002']: THREE.Mesh;
		['Macbook_Pro_16_Display_Base_Space-Black002']: THREE.Mesh;
		['Macbook_Pro_16_Display_Screen_Space-Black002']: THREE.Mesh;
		['Macbook_Pro_16_Keyboard_Space-Black002']: THREE.Mesh;
		['Macbook_Pro_16_Stand_Space-Black002']: THREE.Mesh;
		['Macbook_Pro_16_Case_Space-Black003']: THREE.Mesh;
		['Macbook_Pro_16_Display_Base_Space-Black003']: THREE.Mesh;
		['Macbook_Pro_16_Display_Screen_Space-Black003']: THREE.Mesh;
		['Macbook_Pro_16_Keyboard_Space-Black003']: THREE.Mesh;
		['Macbook_Pro_16_Stand_Space-Black003']: THREE.Mesh;
		['Macbook_Pro_16_Case_Space-Black004']: THREE.Mesh;
		['Macbook_Pro_16_Display_Base_Space-Black004']: THREE.Mesh;
		['Macbook_Pro_16_Display_Screen_Space-Black004']: THREE.Mesh;
		['Macbook_Pro_16_Keyboard_Space-Black004']: THREE.Mesh;
		['Macbook_Pro_16_Stand_Space-Black004']: THREE.Mesh;
	};
	materials: {
		['Macbook_Pro_16_Case_Space-Black']: THREE.MeshStandardMaterial;
		['Macbook_Pro_16_Display_Base_Space-Black']: THREE.MeshStandardMaterial;
		['Macbook_Pro_16_Display_Screen_Space-Black']: THREE.MeshStandardMaterial;
		['Macbook_Pro_16_Keyboard_Space-Black']: THREE.MeshStandardMaterial;
		['Macbook_Pro_16_Stand_Space-Black']: THREE.MeshStandardMaterial;
	};
};

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(
	props: { scrollable?: boolean; distances?: number[] } & JSX.IntrinsicElements['group']
) {
	const { frameloop, dev, mobile } = useContext(UserContextProvider);
	const {
		timestamp,
		scrollSpeed,
		scrollDirection,
		scrolling,
		activeObject,
		clipDuration,
		setClipDuration,
	} = useContext(InputContextProvider);
	const { scrollable } = props.scrollable ? props : { scrollable: false };
	const scroll = useScroll();
	const { clock, controls, camera, scene } = useThree();
	const { nodes, materials } = useGLTF(
		'/../../models/meshes/MacbookM4/MacbookM4.gltf'
	) as GLTFResult;
	return (
		<group {...props} dispose={null}>
			{/* <spotLight intensity={0.7} angle={Math.PI / 2} penumbra={0.15}  position={[0, 0.112, -0.106]} rotation={[2.618, 0, 0]} userData={{ name: 'point' }} /> */}
			<spotLight
				intensity={1}
				angle={Math.PI / 2}
				penumbra={0.15} // this
				position={[0, 0.112, -0.106]}
				rotation={[Math.PI * 0.22, 0, 0]}
				userData={{ name: 'point' }}
			/>

			<Detailed distances={props.distances || [0, 4, 8, 12]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes['Macbook_Pro_16_Case_Space-Black001'].geometry}
					material={materials['Macbook_Pro_16_Case_Space-Black']}
					position={[-0.03, 0, 0]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.01}
					userData={{ name: 'Macbook_Pro_16_Case_Space-Black.001' }}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes['Macbook_Pro_16_Display_Base_Space-Black001'].geometry}
						material={materials['Macbook_Pro_16_Display_Base_Space-Black']}
						position={[3.072, -4.999, -0.193]}
						rotation={[-2.072, 0, 0]}
						userData={{ name: 'Macbook_Pro_16_Display_Base_Space-Black.001' }}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes['Macbook_Pro_16_Display_Screen_Space-Black001'].geometry
							}
							material={materials['Macbook_Pro_16_Display_Screen_Space-Black']}
							position={[0, 0, -0.023]}
							userData={{ name: 'Macbook_Pro_16_Display_Screen_Space-Black.001' }}
							onClick={pointerEventHandlers.handleClick}
							onContextMenu={pointerEventHandlers.handleContextMenu}
							onDoubleClick={pointerEventHandlers.handleDoubleClick}
							onWheel={pointerEventHandlers.handleWheel}
							onPointerUp={pointerEventHandlers.handlePointerUp}
							onPointerDown={pointerEventHandlers.handlePointerDown}
							onPointerOver={pointerEventHandlers.handlePointerOver}
							onPointerOut={pointerEventHandlers.handlePointerOut}
							onPointerEnter={pointerEventHandlers.handlePointerEnter}
							onPointerLeave={pointerEventHandlers.handlePointerLeave}
							onPointerMove={pointerEventHandlers.handlePointerMove}
							onPointerMissed={pointerEventHandlers.handlePointerMissed}
							onUpdate={pointerEventHandlers.handleUpdate}
						/>
					</mesh>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes['Macbook_Pro_16_Keyboard_Space-Black001'].geometry}
						material={materials['Macbook_Pro_16_Keyboard_Space-Black']}
						position={[3.077, 2.068, -0.495]}
						userData={{ name: 'Macbook_Pro_16_Keyboard_Space-Black.001' }}
						onClick={pointerEventHandlers.handleClick}
						onContextMenu={pointerEventHandlers.handleContextMenu}
						onDoubleClick={pointerEventHandlers.handleDoubleClick}
						onWheel={pointerEventHandlers.handleWheel}
						onPointerUp={pointerEventHandlers.handlePointerUp}
						onPointerDown={pointerEventHandlers.handlePointerDown}
						onPointerOver={pointerEventHandlers.handlePointerOver}
						onPointerOut={pointerEventHandlers.handlePointerOut}
						onPointerEnter={pointerEventHandlers.handlePointerEnter}
						onPointerLeave={pointerEventHandlers.handlePointerLeave}
						onPointerMove={pointerEventHandlers.handlePointerMove}
						onPointerMissed={pointerEventHandlers.handlePointerMissed}
						onUpdate={pointerEventHandlers.handleUpdate}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes['Macbook_Pro_16_Stand_Space-Black001'].geometry}
						material={materials['Macbook_Pro_16_Stand_Space-Black']}
						position={[-0.357, 4.627, 0.247]}
						userData={{ name: 'Macbook_Pro_16_Stand_Space-Black.001' }}
						onClick={pointerEventHandlers.handleClick}
						onContextMenu={pointerEventHandlers.handleContextMenu}
						onDoubleClick={pointerEventHandlers.handleDoubleClick}
						onWheel={pointerEventHandlers.handleWheel}
						onPointerUp={pointerEventHandlers.handlePointerUp}
						onPointerDown={pointerEventHandlers.handlePointerDown}
						onPointerOver={pointerEventHandlers.handlePointerOver}
						onPointerOut={pointerEventHandlers.handlePointerOut}
						onPointerEnter={pointerEventHandlers.handlePointerEnter}
						onPointerLeave={pointerEventHandlers.handlePointerLeave}
						onPointerMove={pointerEventHandlers.handlePointerMove}
						onPointerMissed={pointerEventHandlers.handlePointerMissed}
						onUpdate={pointerEventHandlers.handleUpdate}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes['Macbook_Pro_16_Case_Space-Black002'].geometry}
					material={materials['Macbook_Pro_16_Case_Space-Black']}
					position={[-0.03, 0, 0]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.01}
					userData={{ name: 'Macbook_Pro_16_Case_Space-Black.002' }}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes['Macbook_Pro_16_Display_Base_Space-Black002'].geometry}
						material={materials['Macbook_Pro_16_Display_Base_Space-Black']}
						position={[3.072, -4.999, -0.193]}
						rotation={[-2.072, 0, 0]}
						userData={{ name: 'Macbook_Pro_16_Display_Base_Space-Black.002' }}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes['Macbook_Pro_16_Display_Screen_Space-Black002'].geometry
							}
							material={materials['Macbook_Pro_16_Display_Screen_Space-Black']}
							position={[0, 0, -0.023]}
							userData={{ name: 'Macbook_Pro_16_Display_Screen_Space-Black.002' }}
							onClick={pointerEventHandlers.handleClick}
							onContextMenu={pointerEventHandlers.handleContextMenu}
							onDoubleClick={pointerEventHandlers.handleDoubleClick}
							onWheel={pointerEventHandlers.handleWheel}
							onPointerUp={pointerEventHandlers.handlePointerUp}
							onPointerDown={pointerEventHandlers.handlePointerDown}
							onPointerOver={pointerEventHandlers.handlePointerOver}
							onPointerOut={pointerEventHandlers.handlePointerOut}
							onPointerEnter={pointerEventHandlers.handlePointerEnter}
							onPointerLeave={pointerEventHandlers.handlePointerLeave}
							onPointerMove={pointerEventHandlers.handlePointerMove}
							onPointerMissed={pointerEventHandlers.handlePointerMissed}
							onUpdate={pointerEventHandlers.handleUpdate}
						/>
					</mesh>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes['Macbook_Pro_16_Keyboard_Space-Black002'].geometry}
						material={materials['Macbook_Pro_16_Keyboard_Space-Black']}
						position={[3.077, 2.068, -0.495]}
						userData={{ name: 'Macbook_Pro_16_Keyboard_Space-Black.002' }}
						onClick={pointerEventHandlers.handleClick}
						onContextMenu={pointerEventHandlers.handleContextMenu}
						onDoubleClick={pointerEventHandlers.handleDoubleClick}
						onWheel={pointerEventHandlers.handleWheel}
						onPointerUp={pointerEventHandlers.handlePointerUp}
						onPointerDown={pointerEventHandlers.handlePointerDown}
						onPointerOver={pointerEventHandlers.handlePointerOver}
						onPointerOut={pointerEventHandlers.handlePointerOut}
						onPointerEnter={pointerEventHandlers.handlePointerEnter}
						onPointerLeave={pointerEventHandlers.handlePointerLeave}
						onPointerMove={pointerEventHandlers.handlePointerMove}
						onPointerMissed={pointerEventHandlers.handlePointerMissed}
						onUpdate={pointerEventHandlers.handleUpdate}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes['Macbook_Pro_16_Stand_Space-Black002'].geometry}
						material={materials['Macbook_Pro_16_Stand_Space-Black']}
						position={[-0.357, 4.627, 0.247]}
						userData={{ name: 'Macbook_Pro_16_Stand_Space-Black.002' }}
						onClick={pointerEventHandlers.handleClick}
						onContextMenu={pointerEventHandlers.handleContextMenu}
						onDoubleClick={pointerEventHandlers.handleDoubleClick}
						onWheel={pointerEventHandlers.handleWheel}
						onPointerUp={pointerEventHandlers.handlePointerUp}
						onPointerDown={pointerEventHandlers.handlePointerDown}
						onPointerOver={pointerEventHandlers.handlePointerOver}
						onPointerOut={pointerEventHandlers.handlePointerOut}
						onPointerEnter={pointerEventHandlers.handlePointerEnter}
						onPointerLeave={pointerEventHandlers.handlePointerLeave}
						onPointerMove={pointerEventHandlers.handlePointerMove}
						onPointerMissed={pointerEventHandlers.handlePointerMissed}
						onUpdate={pointerEventHandlers.handleUpdate}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes['Macbook_Pro_16_Case_Space-Black003'].geometry}
					material={materials['Macbook_Pro_16_Case_Space-Black']}
					position={[-0.03, 0, 0]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.01}
					userData={{ name: 'Macbook_Pro_16_Case_Space-Black.003' }}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes['Macbook_Pro_16_Display_Base_Space-Black003'].geometry}
						material={materials['Macbook_Pro_16_Display_Base_Space-Black']}
						position={[3.072, -4.999, -0.193]}
						rotation={[-2.072, 0, 0]}
						userData={{ name: 'Macbook_Pro_16_Display_Base_Space-Black.003' }}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes['Macbook_Pro_16_Display_Screen_Space-Black003'].geometry
							}
							material={materials['Macbook_Pro_16_Display_Screen_Space-Black']}
							position={[0, 0, -0.023]}
							userData={{ name: 'Macbook_Pro_16_Display_Screen_Space-Black.003' }}
							onClick={pointerEventHandlers.handleClick}
							onContextMenu={pointerEventHandlers.handleContextMenu}
							onDoubleClick={pointerEventHandlers.handleDoubleClick}
							onWheel={pointerEventHandlers.handleWheel}
							onPointerUp={pointerEventHandlers.handlePointerUp}
							onPointerDown={pointerEventHandlers.handlePointerDown}
							onPointerOver={pointerEventHandlers.handlePointerOver}
							onPointerOut={pointerEventHandlers.handlePointerOut}
							onPointerEnter={pointerEventHandlers.handlePointerEnter}
							onPointerLeave={pointerEventHandlers.handlePointerLeave}
							onPointerMove={pointerEventHandlers.handlePointerMove}
							onPointerMissed={pointerEventHandlers.handlePointerMissed}
							onUpdate={pointerEventHandlers.handleUpdate}
						/>
					</mesh>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes['Macbook_Pro_16_Keyboard_Space-Black003'].geometry}
						material={materials['Macbook_Pro_16_Keyboard_Space-Black']}
						position={[3.077, 2.068, -0.495]}
						userData={{ name: 'Macbook_Pro_16_Keyboard_Space-Black.003' }}
						onClick={pointerEventHandlers.handleClick}
						onContextMenu={pointerEventHandlers.handleContextMenu}
						onDoubleClick={pointerEventHandlers.handleDoubleClick}
						onWheel={pointerEventHandlers.handleWheel}
						onPointerUp={pointerEventHandlers.handlePointerUp}
						onPointerDown={pointerEventHandlers.handlePointerDown}
						onPointerOver={pointerEventHandlers.handlePointerOver}
						onPointerOut={pointerEventHandlers.handlePointerOut}
						onPointerEnter={pointerEventHandlers.handlePointerEnter}
						onPointerLeave={pointerEventHandlers.handlePointerLeave}
						onPointerMove={pointerEventHandlers.handlePointerMove}
						onPointerMissed={pointerEventHandlers.handlePointerMissed}
						onUpdate={pointerEventHandlers.handleUpdate}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes['Macbook_Pro_16_Stand_Space-Black003'].geometry}
						material={materials['Macbook_Pro_16_Stand_Space-Black']}
						position={[-0.357, 4.627, 0.247]}
						userData={{ name: 'Macbook_Pro_16_Stand_Space-Black.003' }}
						onClick={pointerEventHandlers.handleClick}
						onContextMenu={pointerEventHandlers.handleContextMenu}
						onDoubleClick={pointerEventHandlers.handleDoubleClick}
						onWheel={pointerEventHandlers.handleWheel}
						onPointerUp={pointerEventHandlers.handlePointerUp}
						onPointerDown={pointerEventHandlers.handlePointerDown}
						onPointerOver={pointerEventHandlers.handlePointerOver}
						onPointerOut={pointerEventHandlers.handlePointerOut}
						onPointerEnter={pointerEventHandlers.handlePointerEnter}
						onPointerLeave={pointerEventHandlers.handlePointerLeave}
						onPointerMove={pointerEventHandlers.handlePointerMove}
						onPointerMissed={pointerEventHandlers.handlePointerMissed}
						onUpdate={pointerEventHandlers.handleUpdate}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes['Macbook_Pro_16_Case_Space-Black004'].geometry}
					material={materials['Macbook_Pro_16_Case_Space-Black']}
					position={[-0.03, 0, 0]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.01}
					userData={{ name: 'Macbook_Pro_16_Case_Space-Black.004' }}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes['Macbook_Pro_16_Display_Base_Space-Black004'].geometry}
						material={materials['Macbook_Pro_16_Display_Base_Space-Black']}
						position={[3.072, -4.999, -0.193]}
						rotation={[-2.072, 0, 0]}
						userData={{ name: 'Macbook_Pro_16_Display_Base_Space-Black.004' }}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes['Macbook_Pro_16_Display_Screen_Space-Black004'].geometry
							}
							material={materials['Macbook_Pro_16_Display_Screen_Space-Black']}
							position={[0, 0, -0.023]}
							userData={{ name: 'Macbook_Pro_16_Display_Screen_Space-Black.004' }}
							onClick={pointerEventHandlers.handleClick}
							onContextMenu={pointerEventHandlers.handleContextMenu}
							onDoubleClick={pointerEventHandlers.handleDoubleClick}
							onWheel={pointerEventHandlers.handleWheel}
							onPointerUp={pointerEventHandlers.handlePointerUp}
							onPointerDown={pointerEventHandlers.handlePointerDown}
							onPointerOver={pointerEventHandlers.handlePointerOver}
							onPointerOut={pointerEventHandlers.handlePointerOut}
							onPointerEnter={pointerEventHandlers.handlePointerEnter}
							onPointerLeave={pointerEventHandlers.handlePointerLeave}
							onPointerMove={pointerEventHandlers.handlePointerMove}
							onPointerMissed={pointerEventHandlers.handlePointerMissed}
							onUpdate={pointerEventHandlers.handleUpdate}
						/>
					</mesh>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes['Macbook_Pro_16_Keyboard_Space-Black004'].geometry}
						material={materials['Macbook_Pro_16_Keyboard_Space-Black']}
						position={[3.077, 2.068, -0.495]}
						userData={{ name: 'Macbook_Pro_16_Keyboard_Space-Black.004' }}
						onClick={pointerEventHandlers.handleClick}
						onContextMenu={pointerEventHandlers.handleContextMenu}
						onDoubleClick={pointerEventHandlers.handleDoubleClick}
						onWheel={pointerEventHandlers.handleWheel}
						onPointerUp={pointerEventHandlers.handlePointerUp}
						onPointerDown={pointerEventHandlers.handlePointerDown}
						onPointerOver={pointerEventHandlers.handlePointerOver}
						onPointerOut={pointerEventHandlers.handlePointerOut}
						onPointerEnter={pointerEventHandlers.handlePointerEnter}
						onPointerLeave={pointerEventHandlers.handlePointerLeave}
						onPointerMove={pointerEventHandlers.handlePointerMove}
						onPointerMissed={pointerEventHandlers.handlePointerMissed}
						onUpdate={pointerEventHandlers.handleUpdate}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes['Macbook_Pro_16_Stand_Space-Black004'].geometry}
						material={materials['Macbook_Pro_16_Stand_Space-Black']}
						position={[-0.357, 4.627, 0.247]}
						userData={{ name: 'Macbook_Pro_16_Stand_Space-Black.004' }}
						onClick={pointerEventHandlers.handleClick}
						onContextMenu={pointerEventHandlers.handleContextMenu}
						onDoubleClick={pointerEventHandlers.handleDoubleClick}
						onWheel={pointerEventHandlers.handleWheel}
						onPointerUp={pointerEventHandlers.handlePointerUp}
						onPointerDown={pointerEventHandlers.handlePointerDown}
						onPointerOver={pointerEventHandlers.handlePointerOver}
						onPointerOut={pointerEventHandlers.handlePointerOut}
						onPointerEnter={pointerEventHandlers.handlePointerEnter}
						onPointerLeave={pointerEventHandlers.handlePointerLeave}
						onPointerMove={pointerEventHandlers.handlePointerMove}
						onPointerMissed={pointerEventHandlers.handlePointerMissed}
						onUpdate={pointerEventHandlers.handleUpdate}
					/>
				</mesh>
			</Detailed>
		</group>
	);
}

useGLTF.preload('/../../models/meshes/MacbookM4/MacbookM4.gltf');
