/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /Users/thomasmatlock/Documents/Github/portal-threejs/public/models/meshes/Object29/Object29.gltf --output /Users/thomasmatlock/Documents/Github/portal-threejs/models/Object29.tsx -r /models/meshes/Object29 -t --resolution 512 --shadows --meta --keepmeshes --keepmaterials 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib';
import { useFrame, useThree } from "@react-three/fiber";
import { useScroll, Detailed } from '@react-three/drei';
import { easing, geometry } from 'maath';
import UserContextProvider from '@/context/userContext';
import InputContextProvider from '@/context/inputContext';
import { useContext, useState } from 'react';
import { useOptimizedPointerEvents } from '@/shared/pointer/usePointerEvents';
import { useMeshLoad } from '@/shared/useMeshLoad';
        

type GLTFResult = GLTF & {
  nodes: {
    Object29_LOD0: THREE.Mesh
  }
  materials: {
    MapstestchmbA00glassglasswindowRefract01: THREE.MeshStandardMaterial
  }
}

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: {scrollable?: boolean, distances?: number[], 	pointerEvents?: boolean | string} & JSX.IntrinsicElements['group']) {
  
    const { frameloop, dev, mobile } = useContext(UserContextProvider);
    const { timestamp, scrollSpeed, scrollDirection, scrolling, activeObject, clipDuration, setClipDuration } = useContext(InputContextProvider);
    const { scrollable, pointerEvents } = props;
    const scroll = useScroll();
    const { clock, controls, camera, scene } = useThree();
	const pointerName = typeof pointerEvents === 'string' ? pointerEvents : 'object29';
	const optimizedPointerProps = useOptimizedPointerEvents(pointerName);
	const pointerProps = pointerEvents ? optimizedPointerProps : {};
    const { nodes, materials } = useGLTF('/../../models/meshes/Object29/Object29.gltf') as GLTFResult
  
	

	
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Object29_LOD0.geometry} material={materials.MapstestchmbA00glassglasswindowRefract01} position={[-4.829, 6.096, 6.096]} userData={{ name: 'Object29_LOD0' }} 
										{...pointerProps}
				 />
    </group>
  )
}

useGLTF.preload('/../../models/meshes/Object29/Object29.gltf')
