/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /Users/thomasmatlock/Documents/Github/portal-threejs/public/models/meshes/Object13/Object13.gltf --output /Users/thomasmatlock/Documents/Github/portal-threejs/models/Object13.tsx -r /models/meshes/Object13 -t --resolution 512 --shadows --meta --keepmeshes --keepmaterials 
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { RigidBody } from '@react-three/rapier';
import { useFrame, useThree } from '@react-three/fiber';
import { useScroll, Detailed } from '@react-three/drei';
import { easing, geometry } from 'maath';
import UserContextProvider from '@/context/userContext';
import InputContextProvider from '@/context/inputContext';
import { useContext, useState } from 'react';
import { useOptimizedPointerEvents } from '@/shared/pointer/usePointerEvents';
import { useMeshLoad } from '@/shared/useMeshLoad';

type GLTFResult = GLTF & {
	nodes: {
		Object13_LOD0: THREE.Mesh;
	};
	materials: {
		SignagesignageBorder: THREE.MeshStandardMaterial;
	};
};

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(
	props: {
		scrollable?: boolean;
		distances?: number[];
		pointerEvents?: boolean | string;
	} & JSX.IntrinsicElements['group']
) {
	const { frameloop, dev, mobile } = useContext(UserContextProvider);
	const { interacted, setInteracted } = useContext(InputContextProvider);
	const { scrollable, pointerEvents } = props;
	const scroll = useScroll();
	const { clock, controls, camera, scene } = useThree();
	const pointerName = typeof pointerEvents === 'string' ? pointerEvents : 'object13';
	const optimizedPointerProps = useOptimizedPointerEvents(pointerName);
	const pointerProps = pointerEvents ? optimizedPointerProps : {};
	const { nodes, materials } = useGLTF(
		'/../../models/meshes/Object13/Object13.gltf'
	) as GLTFResult;

	return (
		<group {...props} dispose={null}>
			<RigidBody type="fixed" colliders={false}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object13_LOD0.geometry}
					material={materials.SignagesignageBorder}
					position={[-17.031, 3.962, 18.212]}
					userData={{ name: 'Object13_LOD0' }}
					{...pointerProps}
				/>
			</RigidBody>
		</group>
	);
}

useGLTF.preload('/../../models/meshes/Object13/Object13.gltf');
